language: ruby
rvm:
  - 2.0.0
script: rake ci
before_script:
  - sudo apt-get install -qq libevent-dev libncurses-dev
  - git clone git://git.code.sf.net/p/tmux/tmux-code tmux
  - cd tmux
  - sh autogen.sh
  - ./configure && make && sudo make install
  - cd ..
  - export TRAVIS=1
  - tmux new -d
before_install:
  - sudo apt-get install -qq zsh tmux
